# Site settings
title: NAOMI & RAZE
header-img: img/home-bg.jpg
email: twinemenbox@gmail.com
copyright_name: NAOMI & RAZE
description: "Блог разработчиков."
baseurl: ""
url: "http://triple4.github.io"
twitter_username: naomiraze
github_username:  naomiraze

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jemoji]
